from typing import Any

from app.api_execution.schemas import APIAssertion, APIExtraction, APITestCaseDsl, APITestStep


POSTMAN_SCHEMA = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"


def generate_postman_collection(script: APITestCaseDsl) -> dict[str, Any]:
    return {
        "info": {
            "name": script.name or "OpenMelon API Collection",
            "schema": POSTMAN_SCHEMA,
            "description": "Generated by OpenMelon API Automation.",
        },
        "variable": _collection_variables(script),
        "item": [_step_to_item(step) for step in script.steps],
    }


def _collection_variables(script: APITestCaseDsl) -> list[dict[str, Any]]:
    variables = [{"key": "baseUrl", "value": script.base_url or "http://localhost:8000"}]
    for key, value in (script.variables or {}).items():
        variables.append({"key": key, "value": value})
    return variables


def _step_to_item(step: APITestStep) -> dict[str, Any]:
    item = {
        "name": step.name or f"{step.method} {step.path}",
        "request": {
            "method": step.method.upper(),
            "header": _headers(step.headers),
            "url": _url(step.path, step.query),
        },
        "event": [{"listen": "test", "script": {"type": "text/javascript", "exec": _test_script(step)}}],
    }
    body = _body(step.body)
    if body:
        item["request"]["body"] = body
    return item


def _headers(headers: dict[str, Any]) -> list[dict[str, str]]:
    return [{"key": str(key), "value": _postman_vars(value)} for key, value in (headers or {}).items()]


def _url(path: str, query: dict[str, Any]) -> dict[str, Any]:
    normalized_path = path.lstrip("/")
    url = {
        "raw": "{{baseUrl}}/" + normalized_path,
        "host": ["{{baseUrl}}"],
        "path": [part for part in normalized_path.split("/") if part],
    }
    if query:
        url["query"] = [{"key": str(key), "value": _postman_vars(value)} for key, value in query.items()]
    return url


def _body(body: Any) -> dict[str, Any] | None:
    if body is None:
        return None
    if isinstance(body, str):
        return {"mode": "raw", "raw": _postman_vars(body)}
    return {
        "mode": "raw",
        "raw": _json_dumps_with_postman_vars(body),
        "options": {"raw": {"language": "json"}},
    }


def _test_script(step: APITestStep) -> list[str]:
    lines = [
        f'pm.test("{step.name or step.id} request completed", function () {{',
        "  pm.expect(pm.response).to.exist;",
        "});",
    ]
    for assertion in step.assertions or []:
        lines.extend(_assertion_lines(assertion))
    for extraction in step.extractions or []:
        lines.extend(_extraction_lines(extraction))
    return lines


def _assertion_lines(assertion: APIAssertion) -> list[str]:
    expected = assertion.expected if assertion.expected is not None else assertion.value
    if assertion.type == "status_code":
        return [
            f'pm.test("status code is {expected}", function () {{',
            f"  pm.response.to.have.status({int(expected)});",
            "});",
        ]
    if assertion.type == "status_code_not":
        return [
            f'pm.test("status code is not {expected}", function () {{',
            f"  pm.expect(pm.response.code).to.not.eql({int(expected)});",
            "});",
        ]
    if assertion.type == "status_code_in":
        return [
            'pm.test("status code is expected", function () {',
            f"  pm.expect({expected or []}).to.include(pm.response.code);",
            "});",
        ]
    if assertion.type == "status_code_not_in":
        return [
            'pm.test("status code is not blocked", function () {',
            f"  pm.expect({expected or []}).to.not.include(pm.response.code);",
            "});",
        ]
    if assertion.type == "body_contains":
        return [
            'pm.test("body contains expected text", function () {',
            f"  pm.expect(pm.response.text()).to.include({expected!r});",
            "});",
        ]
    if assertion.type == "body_not_contains":
        return [
            'pm.test("body does not contain blocked text", function () {',
            f"  pm.expect(pm.response.text()).to.not.include({expected!r});",
            "});",
        ]
    if assertion.type == "json_path_exists":
        return [
            'pm.test("json path exists", function () {',
            "  const json = pm.response.json();",
            f"  pm.expect(readPath(json, {assertion.path!r})).to.not.equal(undefined);",
            "});",
            *_read_path_helper(),
        ]
    if assertion.type == "json_path_not_exists":
        return [
            'pm.test("json path does not exist", function () {',
            "  const json = pm.response.json();",
            f"  pm.expect(readPath(json, {assertion.path!r})).to.equal(undefined);",
            "});",
            *_read_path_helper(),
        ]
    if assertion.type == "json_path_equals":
        return [
            'pm.test("json path equals expected", function () {',
            "  const json = pm.response.json();",
            f"  pm.expect(readPath(json, {assertion.path!r})).to.eql({expected!r});",
            "});",
            *_read_path_helper(),
        ]
    if assertion.type == "header_equals":
        return [
            'pm.test("header equals expected", function () {',
            f"  pm.expect(pm.response.headers.get({assertion.path!r})).to.eql({expected!r});",
            "});",
        ]
    if assertion.type == "header_exists":
        return [
            'pm.test("header exists", function () {',
            f"  pm.expect(pm.response.headers.get({assertion.path!r})).to.not.equal(undefined);",
            "});",
        ]
    if assertion.type == "header_contains":
        return [
            'pm.test("header contains expected text", function () {',
            f"  pm.expect(pm.response.headers.get({assertion.path!r}) || '').to.include({expected!r});",
            "});",
        ]
    if assertion.type == "response_time_lt":
        return [
            'pm.test("response time below threshold", function () {',
            f"  pm.expect(pm.response.responseTime).to.be.below({int(expected)});",
            "});",
        ]
    return []


def _extraction_lines(extraction: APIExtraction) -> list[str]:
    name = extraction.name.strip()
    if not name:
        return []
    if extraction.source == "header":
        return [f"pm.collectionVariables.set({name!r}, pm.response.headers.get({(extraction.path or '')!r}));"]
    if extraction.source == "status_code":
        return [f"pm.collectionVariables.set({name!r}, pm.response.code);"]
    if extraction.source == "body_text":
        return [f"pm.collectionVariables.set({name!r}, pm.response.text());"]
    return [
        "const extractionJson = pm.response.json();",
        *_read_path_helper(),
        f"pm.collectionVariables.set({name!r}, readPath(extractionJson, {(extraction.path or '')!r}));",
    ]


def _read_path_helper() -> list[str]:
    return [
        "function readPath(data, path) {",
        "  if (!path) return data;",
        "  const normalized = path.startsWith('$.') ? path.slice(2) : path.replace(/^\\./, '');",
        "  return normalized.split('.').reduce((acc, part) => {",
        "    if (acc === undefined || acc === null) return undefined;",
        "    if (Array.isArray(acc) && /^\\d+$/.test(part)) return acc[Number(part)];",
        "    return acc[part];",
        "  }, data);",
        "}",
    ]


def _postman_vars(value: Any) -> str:
    # Preserve Postman {{variable}} syntax as-is (same as DSL {{var}} syntax)
    return str(value)


def _json_dumps_with_postman_vars(value: Any) -> str:
    import json

    return json.dumps(value, ensure_ascii=False, indent=2)
