import json
import re
from typing import Any

from app.api_execution.schemas import APITestCaseDsl


def generate_pytest_script(script: APITestCaseDsl) -> str:
    payload = script.model_dump()
    return f'''"""
Generated by OpenMelon API Automation.

Run:
    pip install pytest httpx
    pytest api-test-script.py -v
"""

import re

import httpx


TEST_SCRIPT = {json.dumps(payload, ensure_ascii=False, indent=2)}


VARIABLE_PATTERN = re.compile(r"\\{{\\{{\\s*([\\w.-]+)\\s*\\}}\\}}")


def substitute(value, variables):
    if isinstance(value, dict):
        return {{key: substitute(item, variables) for key, item in value.items()}}
    if isinstance(value, list):
        return [substitute(item, variables) for item in value]
    if not isinstance(value, str):
        return value
    full_match = VARIABLE_PATTERN.fullmatch(value)
    if full_match:
        return variables.get(full_match.group(1), value)
    return VARIABLE_PATTERN.sub(lambda match: str(variables.get(match.group(1), match.group(0))), value)


def build_url(base_url, step, variables):
    path = str(substitute(step.get("path", ""), variables))
    for key, value in substitute(step.get("path_params", {{}}), variables).items():
        path = path.replace("{{" + key + "}}", str(value))
    return base_url.rstrip("/") + "/" + path.lstrip("/")


def read_path(data, path):
    if not path:
        return data
    current = data
    normalized_path = path[2:] if path.startswith("$.") else path.lstrip(".")
    for part in normalized_path.split("."):
        if isinstance(current, dict):
            current = current.get(part)
        elif isinstance(current, list) and part.isdigit():
            index = int(part)
            current = current[index] if 0 <= index < len(current) else None
        else:
            return None
        if current is None:
            return None
    return current


def extract_value(response, source, path):
    if source == "status_code":
        return response.status_code
    if source == "header":
        return response.headers.get(path or "")
    if source == "body_text":
        return response.text
    try:
        body = response.json()
    except Exception:
        return None
    return read_path(body, path)


def run_assertions(step, response, duration_ms):
    assertions = step.get("assertions") or [{{"type": "status_code_in", "expected": [200, 299]}}]
    for assertion in assertions:
        assertion_type = assertion.get("type")
        expected = assertion.get("expected", assertion.get("value"))
        if assertion_type == "status_code":
            assert response.status_code == expected
        elif assertion_type == "status_code_in":
            assert response.status_code in expected
        elif assertion_type == "body_contains":
            assert str(expected) in response.text
        elif assertion_type == "response_time_lt":
            assert duration_ms < int(expected)
        elif assertion_type == "json_path_exists":
            assert extract_value(response, "body", assertion.get("path")) is not None
        elif assertion_type == "json_path_equals":
            assert extract_value(response, "body", assertion.get("path")) == expected
        elif assertion_type == "header_equals":
            assert response.headers.get(assertion.get("path") or "") == expected


def test_api_script():
    variables = dict(TEST_SCRIPT.get("variables") or {{}})
    base_url = TEST_SCRIPT.get("base_url") or "http://localhost:8000"
    with httpx.Client(timeout=30) as client:
        for step in TEST_SCRIPT.get("steps", []):
            headers = substitute(step.get("headers", {{}}), variables)
            query = substitute(step.get("query", {{}}), variables)
            body = substitute(step.get("body"), variables)
            url = build_url(base_url, step, variables)
            response = client.request(
                step.get("method", "GET"),
                url,
                headers={{str(key): str(value) for key, value in headers.items()}},
                params=query,
                json=body if isinstance(body, (dict, list)) else None,
                content=body if isinstance(body, str) else None,
            )
            duration_ms = int(response.elapsed.total_seconds() * 1000)
            run_assertions(step, response, duration_ms)
            for extraction in step.get("extractions", []):
                name = (extraction.get("name") or "").strip()
                if name:
                    value = extract_value(response, extraction.get("source", "body"), extraction.get("path"))
                    if value is not None:
                        variables[name] = value
'''


def _safe_filename(name: str) -> str:
    slug = re.sub(r"[^\w\u4e00-\u9fa5-]+", "_", name or "test_api_script").strip("_")
    return slug or "test_api_script"
